"""initial schema

Revision ID: a06fd86f7505
Revises: 
Create Date: 2026-02-13 22:01:45.127651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a06fd86f7505'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_name'), 'areas', ['name'], unique=True)
    op.create_table('calendars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendars_slug'), 'calendars', ['slug'], unique=True)
    op.create_table('commitments',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('metric', sa.Text(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('difficulty', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('busy_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('start_dt', sa.Text(), nullable=False),
    sa.Column('end_dt', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_busy_blocks_calendar_id'), 'busy_blocks', ['calendar_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NOW', 'NEXT', 'WAITING', 'SOMEDAY', 'DONE', 'CANCELED', name='task_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('commitment_id', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('P1', 'P2', 'P3', name='task_priority', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('estimate_min', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('waiting_on', sa.Text(), nullable=True),
    sa.Column('ping_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.CheckConstraint("status != 'WAITING' OR (waiting_on IS NOT NULL AND waiting_on != '' AND ping_at IS NOT NULL)", name='ck_tasks_waiting_requires_fields'),
    sa.CheckConstraint('estimate_min > 0', name='ck_tasks_estimate_min_gt_0'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['commitment_id'], ['commitments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_busy_blocks_calendar_id'), table_name='busy_blocks')
    op.drop_table('busy_blocks')
    op.drop_table('settings')
    op.drop_table('commitments')
    op.drop_index(op.f('ix_calendars_slug'), table_name='calendars')
    op.drop_table('calendars')
    op.drop_index(op.f('ix_areas_name'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
